using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SmartRoutePayment.Application.DTOs.Responses
{
    /// <summary>
    /// Response containing all parameters needed for Angular to post directly to PayOne
    /// Includes SecureHash and TransactionID generated by backend
    /// </summary>
    public class PreparePaymentResponseDto
    {
        /// <summary>
        /// Generated unique Transaction ID
        /// </summary>
        public string TransactionId { get; set; } = string.Empty;

        /// <summary>
        /// Merchant ID (from configuration)
        /// </summary>
        public string MerchantId { get; set; } = string.Empty;

        /// <summary>
        /// Amount in fils/smallest currency unit (e.g., 5000 for 50.00 SAR)
        /// </summary>
        public string Amount { get; set; } = string.Empty;

        /// <summary>
        /// Currency ISO Code (682 for SAR)
        /// </summary>
        public string CurrencyIsoCode { get; set; } = string.Empty;

        /// <summary>
        /// Message ID (1=Payment, 2=PreAuth, 3=Verify)
        /// </summary>
        public string MessageId { get; set; } = string.Empty;

        /// <summary>
        /// Quantity
        /// </summary>
        public string Quantity { get; set; } = string.Empty;

        /// <summary>
        /// Channel (0=Web, 1=Mobile, 2=CallCenter)
        /// </summary>
        public string Channel { get; set; } = string.Empty;

        /// <summary>
        /// Payment Method (1=Card)
        /// </summary>
        public string PaymentMethod { get; set; } = string.Empty;

        /// <summary>
        /// Language (en/ar)
        /// </summary>
        public string Language { get; set; } = string.Empty;

        /// <summary>
        /// Theme ID
        /// </summary>
        public string ThemeId { get; set; } = string.Empty;

        /// <summary>
        /// API Version
        /// </summary>
        public string Version { get; set; } = string.Empty;

        /// <summary>
        /// Generated Secure Hash (SHA256)
        /// Angular will include this when posting to PayOne
        /// </summary>
        public string SecureHash { get; set; } = string.Empty;

        /// <summary>
        /// Payment Description (optional)
        /// </summary>
        public string? PaymentDescription { get; set; }

        /// <summary>
        /// Item ID (optional)
        /// </summary>
        public string? ItemId { get; set; }

        /// <summary>
        /// PayOne Direct Post URL where Angular should post
        /// </summary>
        public string PayoneUrl { get; set; } = string.Empty;

        /// <summary>
        /// Merchant's callback URL where PayOne will send payment response
        /// </summary>
        public string? ResponseBackUrl { get; set; }
    }
}
